services:
  wechat:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-wechat
    container_name: docker-wechat
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/${UID}/pulse/native
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.config/pulse/cookie:/home/wechatuser/.config/pulse/cookie
      - /run/user/${UID}/pulse/native:/run/user/${UID}/pulse/native
    devices:
      - /dev/snd
    user: "${UID}:${GID}"
    # restart: unless-stopped
